steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >
        sleep 45 &&  echo $(gcloud logging read
        "protoPayload.authorizationInfo.permission=compute.machineImages.create"
        --limit 1 --format json --quiet) > _LOG && apt-get update && apt-get
        install -y jq  && echo $(echo "$(cat _LOG)" | jq -r
        '.[0].protoPayload.resourceName | split("/") | .[-1]')  > _IMAGE
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - | 
        if [[ $(cat _IMAGE) == tr-debian-11-v* ]]; then
          gcloud compute instances create debian-11-$(date +%d%h%Y-%H%M | tr '[:upper:]' '[:lower:]') \
            --project=sai-vizag-test \
            --zone=us-central1-a \
            --machine-type=e2-medium \
            --service-account=sai-120@sai-vizag-test.iam.gserviceaccount.com \
            --scopes=https://www.googleapis.com/auth/cloud-platform \
            --source-machine-image=$(cat _IMAGE) \
            --metadata=startup-script-url=gs://tst-bkt-1/startup-script.sh
        else 
          echo "os not supported" 
        fi 
    entrypoint: bash
options:
  logging: CLOUD_LOGGING_ONLY
